# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(466, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(466, 300))
        Form.setMaximumSize(QtCore.QSize(466, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/ship.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 40, 71, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/alien.bmp"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(150, 50, 281, 41))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.edt_username = QtWidgets.QLineEdit(Form)
        self.edt_username.setGeometry(QtCore.QRect(160, 130, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.edt_username.setFont(font)
        self.edt_username.setText("")
        self.edt_username.setMaxLength(32768)
        self.edt_username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.edt_username.setObjectName("edt_username")
        self.edt_password = QtWidgets.QLineEdit(Form)
        self.edt_password.setGeometry(QtCore.QRect(160, 170, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.edt_password.setFont(font)
        self.edt_password.setText("")
        self.edt_password.setObjectName("edt_password")
        self.but_login = QtWidgets.QPushButton(Form)
        self.but_login.setGeometry(QtCore.QRect(200, 230, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.but_login.setFont(font)
        self.but_login.setObjectName("but_login")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        self.label_2.setText(_translate("Form", "黑羽学院数据处理登录"))
        self.edt_username.setPlaceholderText(_translate("Form", "用户名"))
        self.edt_password.setPlaceholderText(_translate("Form", "密码"))
        self.but_login.setText(_translate("Form", "登录"))


# 程序主入口，程序从此处启动pyQt设计的窗体
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    # 创建窗体对象
    MainWindow = QtWidgets.QMainWindow()
    # 创建pyqt设计的窗体对象
    ui = Ui_Form()
    # 调用pyqt 窗体的方法对窗体对象进行初始化设置
    ui.setupUi(MainWindow)
    # 显示窗体
    MainWindow.show()
    # 程序关闭时退出进程
    sys.exit(app.exec_())